# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lackie}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Chisholm"]
  s.date = %q{2010-12-31}
  s.description = %q{Automates remote applications using an HTTP middleman}
  s.email = %q{joshuachisholm@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "features/remote_control.feature",
    "features/step_definitions/lackie_steps.rb",
    "features/support/config.ru",
    "features/support/env.rb",
    "features/support/example_app.rb",
    "features/support/example_app/app.html",
    "lackie.gemspec",
    "lib/lackie.rb",
    "lib/lackie/javascript.rb",
    "lib/lackie/javascript/json2.js",
    "lib/lackie/javascript/surrender.js",
    "lib/lackie/javascript/surrender.rb",
    "lib/lackie/poller.rb",
    "lib/lackie/rack.rb",
    "lib/lackie/rack/middleware.rb",
    "lib/lackie/remote_control.rb",
    "spec/lackie/javascript/surrender_spec.rb",
    "spec/lackie/poller_spec.rb",
    "spec/lackie/rack/middleware_spec.rb",
    "spec/lackie/remote_control_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/joshski/lackie}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Automates remote applications using an HTTP middleman}
  s.test_files = [
    "spec/lackie/javascript/surrender_spec.rb",
    "spec/lackie/poller_spec.rb",
    "spec/lackie/rack/middleware_spec.rb",
    "spec/lackie/remote_control_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<lackie>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, ["~> 1.2.1"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.4.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.2.0"])
      s.add_development_dependency(%q<cucumber>, ["~> 0.10.0"])
      s.add_development_dependency(%q<mongrel>, ["~> 1.1.5"])
      s.add_development_dependency(%q<relevance-rcov>, ["~> 0.9.2.1"])
    else
      s.add_dependency(%q<lackie>, [">= 0"])
      s.add_dependency(%q<rack>, ["~> 1.2.1"])
      s.add_dependency(%q<rest-client>, ["~> 1.4.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0.7"])
      s.add_dependency(%q<rspec>, ["~> 2.2.0"])
      s.add_dependency(%q<cucumber>, ["~> 0.10.0"])
      s.add_dependency(%q<mongrel>, ["~> 1.1.5"])
      s.add_dependency(%q<relevance-rcov>, ["~> 0.9.2.1"])
    end
  else
    s.add_dependency(%q<lackie>, [">= 0"])
    s.add_dependency(%q<rack>, ["~> 1.2.1"])
    s.add_dependency(%q<rest-client>, ["~> 1.4.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0.7"])
    s.add_dependency(%q<rspec>, ["~> 2.2.0"])
    s.add_dependency(%q<cucumber>, ["~> 0.10.0"])
    s.add_dependency(%q<mongrel>, ["~> 1.1.5"])
    s.add_dependency(%q<relevance-rcov>, ["~> 0.9.2.1"])
  end
end

